### ISSUE TITLE
프로젝트 및 이슈 초기 설정

### ISSUE THREAD

**Issue by yonaSeo** [yonaSeo/GAMAGU-iOS#1]
# 🛠️ Issue
프로젝트 및 이슈와 관련된 기본적인 설정을 한다.
# ☑️ Tasks
- [x] Issue 템플릿 설정
- [x] Pull Request 템플릿 설정
- [x] 프로젝트 관련 기타 설정 (스프린트, 마일스톤 등)
- [x] 전체 프로젝트 이슈 등록
