### ISSUE TITLE
Home 페이지 만들기

### ISSUE THREAD

**Issue by yonaSeo** [yonaSeo/GAMAGU-iOS#2]
# 🛠️ Issue
Tab Bar 메뉴의 Home 페이지에 해당하는 뷰를 만든다.
# ☑️ Tasks
- [x] Header 만들기 (Navigation Bar 설정)
- [x] Footer 만들기 (Tab Bar 설정)
- [x] Segmented Control 설정
- [x] Carousel (CollectionView) 만들기
- [x] TableView 만들기
- [x] Add 페이지 만들기
