### ISSUE TITLE
배포 및 앱스토어 등록

### ISSUE THREAD

**Issue by yonaSeo** [yonaSeo/GAMAGU-iOS#8]
# 🛠️ Issue
배포 및 앱스토어 등록/심사 관련 모든 작업을 수행한다.
# ☑️ Tasks
- [x] 모든 브랜치 머지 후 Relase 버전 배포
- [x] 앱스토어 개발자 등록
- [x] 앱스토어 앱 등록/심사/테스트(TestFlight) 관련 작업
